-- IBFT Log ETL - PostgreSQL schema
-- Snapshot cấu trúc từ môi trường chạy hiện tại, không chứa dữ liệu hoặc credential.
-- Dùng cho database trống. Không chạy chồng lên schema đang có khi chưa được DBA kiểm tra.

BEGIN;

CREATE TABLE public.etl_batch (
    batch_id bigint GENERATED ALWAYS AS IDENTITY,
    source_file_name character varying(100) NOT NULL,
    started_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at timestamp without time zone,
    CONSTRAINT etl_batch_pkey PRIMARY KEY (batch_id),
    CONSTRAINT uq_etl_batch_source_file UNIQUE (source_file_name)
);

CREATE TABLE public.stg_event (
    log_header timestamp without time zone,
    request_type character varying(28),
    tracenumber character varying(6),
    pan character varying(19),
    transactionamount character varying(12),
    transmissiondateandtime character varying(10),
    timelocaltranx character varying(6),
    datelocaltranx character varying(4),
    merchanttype character varying(4),
    entrymodecode character varying(3),
    serviceconditioncode character varying(2),
    acceptingidcode character varying(11),
    referencenumber character varying(12),
    terminalid character varying(8),
    merchantid character varying(15),
    merchantname character varying(43),
    merchantlocation character varying(43),
    ibfttype character varying(3),
    bankcode character varying(11),
    bankname character varying(28),
    accountdestnumber character varying(28),
    currencycode character varying(3),
    accounttype character varying(2),
    accountsourcenumber character varying(28),
    channel character varying(10),
    channelcode character varying(2),
    description character varying(210),
    f37 character varying(12),
    approvecode character varying(6),
    datesettlement character varying(4),
    responsecode character varying(2),
    short_filename character varying(100),
    loaded_at timestamp without time zone,
    accountsourcename character varying(210),
    accountsourceaddress character varying(210),
    accountdestname character varying(210)
);

CREATE TABLE public.stg_txn (
    tracenumber character varying(6),
    pan character varying(19),
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    transactionamount character varying(12),
    transmissiondateandtime character varying(10),
    timelocaltranx character varying(6),
    datelocaltranx character varying(4),
    merchanttype character varying(4),
    entrymodecode character varying(3),
    serviceconditioncode character varying(2),
    acceptingidcode character varying(11),
    referencenumber character varying(12),
    terminalid character varying(8),
    merchantid character varying(15),
    merchantname character varying(43),
    merchantlocation character varying(43),
    ibfttype character varying(3),
    bankcode character varying(11),
    bankname character varying(28),
    accountdestnumber character varying(28),
    accountdestname character varying(210),
    currencycode character varying(3),
    accounttype character varying(2),
    accountsourcenumber character varying(28),
    accountsourcename character varying(210),
    accountsourceaddress character varying(210),
    channel character varying(10),
    channelcode character varying(2),
    description character varying(210),
    f37 character varying(12),
    approvecode character varying(6),
    datesettlement character varying(4),
    responsecode character varying(2),
    short_filename character varying(100),
    status character varying(210),
    total_time_s double precision,
    loaded_at timestamp without time zone
);

CREATE TABLE public.ibft_detail (
    detail_id bigint GENERATED ALWAYS AS IDENTITY,
    batch_id bigint NOT NULL,
    log_header timestamp without time zone,
    request_type character varying(28) NOT NULL,
    tracenumber character varying(6) NOT NULL,
    pan character varying(19),
    transactionamount character varying(12),
    transmissiondateandtime character varying(10),
    timelocaltranx character varying(6),
    datelocaltranx character varying(4),
    merchanttype character varying(4),
    entrymodecode character varying(3),
    serviceconditioncode character varying(2),
    acceptingidcode character varying(11),
    referencenumber character varying(12),
    terminalid character varying(8),
    merchantid character varying(15),
    merchantname character varying(43),
    merchantlocation character varying(43),
    ibfttype character varying(3),
    bankcode character varying(11),
    bankname character varying(28),
    accountdestnumber character varying(28),
    currencycode character varying(3),
    accounttype character varying(2),
    accountsourcenumber character varying(28),
    channel character varying(10),
    channelcode character varying(2),
    description character varying(210),
    f37 character varying(12),
    approvecode character varying(6),
    datesettlement character varying(4),
    responsecode character varying(2),
    short_filename character varying(100),
    loaded_at timestamp without time zone,
    accountsourcename character varying(210),
    accountsourceaddress character varying(210),
    accountdestname character varying(210),
    CONSTRAINT ibft_detail_pkey PRIMARY KEY (detail_id),
    CONSTRAINT fk_ibft_detail_batch
        FOREIGN KEY (batch_id) REFERENCES public.etl_batch(batch_id)
);

CREATE TABLE public.ibft_summary (
    summary_id bigint GENERATED ALWAYS AS IDENTITY,
    batch_id bigint NOT NULL,
    tracenumber character varying(6) NOT NULL,
    pan character varying(19),
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    transactionamount character varying(12),
    transmissiondateandtime character varying(10),
    timelocaltranx character varying(6),
    datelocaltranx character varying(4),
    merchanttype character varying(4),
    entrymodecode character varying(3),
    serviceconditioncode character varying(2),
    acceptingidcode character varying(11),
    referencenumber character varying(12),
    terminalid character varying(8),
    merchantid character varying(15),
    merchantname character varying(43),
    merchantlocation character varying(43),
    ibfttype character varying(3),
    bankcode character varying(11),
    bankname character varying(28),
    accountdestnumber character varying(28),
    accountdestname character varying(210),
    currencycode character varying(3),
    accounttype character varying(2),
    accountsourcenumber character varying(28),
    accountsourcename character varying(210),
    accountsourceaddress character varying(210),
    channel character varying(10),
    channelcode character varying(2),
    description character varying(210),
    f37 character varying(12),
    approvecode character varying(6),
    datesettlement character varying(4),
    responsecode character varying(2),
    short_filename character varying(100),
    status character varying(210) NOT NULL,
    total_time_s double precision,
    loaded_at timestamp without time zone,
    CONSTRAINT ibft_summary_pkey PRIMARY KEY (summary_id),
    CONSTRAINT uq_ibft_summary_batch_trace UNIQUE (batch_id, tracenumber),
    CONSTRAINT fk_ibft_summary_batch
        FOREIGN KEY (batch_id) REFERENCES public.etl_batch(batch_id)
);

COMMIT;
